# Generated by Django 4.2.4 on 2023-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_pkmn',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_pkmn',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
